### ISSUE TITLE
It's Tracking empty stone types

### ISSUE THREAD

**Issue by CanisArtorus** [CanisArtorus/ProspectorJournal#2]
option: (config?)
* [ ] discard stone materials / do not add to data set
* [ ] accept stone layers as things to map
* [ ] re-enable deletion of entries

**Comment by CanisArtorus** [comment]
It only happens to rock samples, which are being aggregated per-chunk as it stands.
=> small memory/file size footprint.

**Comment by CanisArtorus** [comment]
As part of the server-side nature of all rock samples, discarding the default rocks (which should be the only basic stones) is easy and appropriate.

**Comment by CanisArtorus** [comment]
The stone layer rocks are not default rocks.
Different filtering will be required.
